# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=264, unique=True)),
                ('LName', models.CharField(max_length=264, unique=True)),
                ('Email', models.CharField(max_length=264, unique=True)),
            ],
        ),
    ]
