# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='user',
            name='FName',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='user',
            name='LName',
            field=models.CharField(max_length=264),
        ),
    ]
